### ISSUE TITLE
是否支持安卓12呢？

### ISSUE THREAD

**Issue by jones-187** [XhyEax/SoftApHelper#1]
很棒的程序，解决了手机做热点ip不固定的痛点。

我有一个问题，安卓12是否兼容呢？（我暂时没有能够测试的设备）

**Comment by mmfmkuang** [comment]
我手头有一台MIUI13（安卓12）的红米note9pro，试过是不兼容的，后来反编译看了一下跟安卓11相比多了点变化，改过后应该能用，但不知道怎么上传……
