### ISSUE TITLE
模块无法固定usb0

### ISSUE THREAD

**Issue by jp5865** [XhyEax/SoftApHelper#10]
手机:天翼1号2020
cpu:紫光展锐 虎贲T7510
问题:无法固定USB0 ip，别的设备也无法连接成功
[EdXposed_Verbose_20230202_091147.txt](https://github.com/XhyEax/SoftApHelper/files/10563875/EdXposed_Verbose_20230202_091147.txt)
[ifconfig.txt](https://github.com/XhyEax/SoftApHelper/files/10563882/ifconfig.txt)

**Comment by XhyEax** [comment]
找不到目标类，Wifi应该也不能固定吧。

使用MT管理器，在/system文件夹下，高级搜索，搜索文件内容：getRandomWifiIPv4Address

然后把搜索结果发一下。

**Comment by jp5865** [comment]
> 找不到目标类，Wifi应该也不能固定吧。
> 
> 使用MT管理器，在/系统文件夹下，高级搜索，搜索文件内容：getRandomWifiIPv4Address
> 
> 然后把搜索结果发布一下。

搜索无结果

**Comment by XhyEax** [comment]
使用的是all版本吗

**Comment by jp5865** [comment]
> 使用的是所有版本吗

对

**Comment by jp5865** [comment]
> 安卓9的usb0 IP，是不是本身就是固定的

我这台是固定192.168.42.xx

**Comment by XhyEax** [comment]
重启后也固定为这个ip？

**Comment by jp5865** [comment]
> 重启动后也固定为这个ip？

嗯
我没用模块也是这个
用的模块也是这个,但连不上了

**Comment by XhyEax** [comment]
这个模块功能就是把随机IP变成固定的。

那你的需求是什么？
usb0本身就是固定的。是想把它改成另一个固定的43.1？
还是说想解决开启模块后，无法连接的问题。

**Comment by jp5865** [comment]
> 这个模块功能就是把随机IP变成固定的。
> 
> 那你的需求是什么？ usb0本身就是固定的。是想把它改成另一个固定的43.1？ 还是说想解决开启模块后，无法连接的问题。

固定IP和无法连接
现在ip随机，USB想打开面板有点麻烦

**Comment by XhyEax** [comment]
根据系统源码，usb热点IP本身就是固定在192.168.42.129的。如果你手机上是随机的，说明厂商魔改了系统源码。

[TetherInterfaceStateMachine.java#207](http://aospxref.com/android-9.0.0_r61/xref/frameworks/base/services/core/java/com/android/server/connectivity/tethering/TetherInterfaceStateMachine.java#207)

```
if (mInterfaceType == ConnectivityManager.TETHERING_USB) {
	ipAsString = USB_NEAR_IFACE_ADDR;
	prefixLen = USB_PREFIX_LENGTH;
} else if (mInterfaceType == ConnectivityManager.TETHERING_WIFI) {
	ipAsString = getRandomWifiIPv4Address();
	prefixLen = WIFI_HOST_IFACE_PREFIX_LENGTH;
}
```

**Comment by jp5865** [comment]
> 根据系统源码，usb热点IP本身就是固定在192.168.42.129的。如果你手机上是随机的，说明厂商魔改了系统源码。
> 
> [TetherInterfaceStateMachine.java#207](http://aospxref.com/android-9.0.0_r61/xref/frameworks/base/services/core/java/com/android/server/connectivity/tethering/TetherInterfaceStateMachine.java#207)
> 
> ```
> if (mInterfaceType == ConnectivityManager.TETHERING_USB) {
> 	ipAsString = USB_NEAR_IFACE_ADDR;
> 	prefixLen = USB_PREFIX_LENGTH;
> } else if (mInterfaceType == ConnectivityManager.TETHERING_WIFI) {
> 	ipAsString = getRandomWifiIPv4Address();
> 	prefixLen = WIFI_HOST_IFACE_PREFIX_LENGTH;
> }
> ```

我这破手机什么都不开源，看来无解了，我继续用热点吧

**Comment by XhyEax** [comment]
由此就需要你提供魔改后的services代码。但是你又说搜不到。

**Comment by XhyEax** [comment]
是arm64的吗？

**Comment by jp5865** [comment]
> 是arm64的吗？

对

**Comment by XhyEax** [comment]
用网盘上传一下`/system/framework/oat/arm64/services.vdex`。

**Comment by XhyEax** [comment]
不开模块。

**Comment by jp5865** [comment]
> 用网盘上传一下`/system/framework/oat/arm64/services.vdex`。

https://app-520.lanzoum.com/iwUBV0mnio5i

**Comment by XhyEax** [comment]
配置ip的代码就是官方的源码，usb热点ip固定为`192.168.42.129`

Hook点 getRandomWifiIPv4Address，也只有wifi热点调用。

可能是别的地方覆盖了这个配置。

**Comment by XhyEax** [comment]
如果只有这个文件调用，usb热点ip就应该固定为`192.168.42.129`，并且模块是不影响usb热点连接情况的。

**Comment by jp5865** [comment]
> 如果只有这个文件调用，usb热点ip就应该固定为`192.168.42.129`，而模块是不影响usb热点连接情况的。

好

**Comment by XhyEax** [comment]
既然wifi热点是可用的，那就只能用wifi热点了。
