### ISSUE TITLE
USB共享的时候ping不通192.168.43.1,完全没网

### ISSUE THREAD

**Issue by wangyucst** [XhyEax/SoftApHelper#12]
USB共享的时候ping不通192.168.43.1,完全没网（下载的1.040all版本）中兴7530N 安卓11
[InProcessTethering.zip](https://github.com/XhyEax/SoftApHelper/files/11206121/InProcessTethering.zip)

**Comment by wangyucst** [comment]
补充：WiFi下一切正常

**Comment by wangyucst** [comment]
> 1.1呢
> […](#)
> ---原始邮件--- 发件人: "wang ***@***.***&gt; 发送时间: 2023年4月12日(周三) 上午9:08 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: Re: [XhyEax/SoftApHelper] USB共享的时候ping不通192.168.43.1,完全没网 (Issue #12) 补充：WiFi下一切正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

1.1在哪里下载呢？我看github上最新版是1.040版本的。

**Comment by XhyEax** [comment]
192.168.1.1



---原始邮件---
发件人: "wang ***@***.***&gt;
发送时间: 2023年4月12日(周三) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] USB共享的时候ping不通192.168.43.1,完全没网 (Issue #12)




  
1.1呢
 …
 ---原始邮件--- 发件人: "wang @.&gt; 发送时间: 2023年4月12日(周三) 上午9:08 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [XhyEax/SoftApHelper] USB共享的时候ping不通192.168.43.1,完全没网 (Issue #12) 补充：WiFi下一切正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt;
  
1.1在哪里下载呢？我看github上最新版是1.040版本的。

**Comment by wangyucst** [comment]
> 192.168.1.1
> […](#)
> ---原始邮件--- 发件人: "wang ***@***.***&gt; 发送时间: 2023年4月12日(周三) 上午10:14 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [XhyEax/SoftApHelper] USB共享的时候ping不通192.168.43.1,完全没网 (Issue #12) 1.1呢 … ---原始邮件--- 发件人: "wang @.&gt; 发送时间: 2023年4月12日(周三) 上午9:08 收件人: @.&gt;; 抄送: @.&gt;; 主题: Re: [XhyEax/SoftApHelper] USB共享的时候ping不通192.168.43.1,完全没网 (Issue #12) 补充：WiFi下一切正常 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: @.&gt; 1.1在哪里下载呢？我看github上最新版是1.040版本的。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

刚才一下脑抽没看明白，又去测试了一下192.168.1.1，也是同样的问题，WiFi下正常，usb共享网络没网。

**Comment by wangyucst** [comment]
解决问题了老哥，手机不能同时开WiFi热点和usb热点，我把WiFi热点关闭之后，usb共享就有网了

**Comment by wangyucst** [comment]
> 我测试了一下发现 同时启用 WLAN共享 / 蓝牙共享 / USB共享 中超过一个的话，只有最开始启用那个可以正常共享。猜测三个网卡都是43.1之后路由不到。 正常未Hook的情况下Android 12 （MIUI 13）的情况下，三者会分配不同网段的IP，蓝牙固定在44.1。 旧版本Android暂时没有机器测试。

确实是这样的，我的安卓11，分配到相同的网段，但后加入的会没网

**Comment by XhyEax** [comment]
行，那我后面更新一下，设置成不同的IP



---原始邮件---
发件人: "wang ***@***.***&gt;
发送时间: 2023年4月12日(周三) 中午11:18
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] USB共享的时候ping不通192.168.43.1,完全没网 (Issue #12)




  
我测试了一下发现 同时启用 WLAN共享 / 蓝牙共享 / USB共享 中超过一个的话，只有最开始启用那个可以正常共享。猜测三个网卡都是43.1之后路由不到。 正常未Hook的情况下Android 12 （MIUI 13）的情况下，三者会分配不同网段的IP，蓝牙固定在44.1。 旧版本Android暂时没有机器测试。
  
确实是这样的，我的安卓11，分配到相同的网段，但后加入的会没网

**Comment by XhyEax** [comment]
`1.0.50`已分配不同IP。

|           Type          |         IP              |
|-------------------------|-----------------------|
| WIFI | WIFI_HOST_IFACE_ADDR  |
| USB  | 192.168.42.1          |
| BlueTooth   | 192.168.44.1          |

**Comment by wangyucst** [comment]
> `1.0.50`已分配不同IP。
> 
> Type	IP
> WIFI	WIFI_HOST_IFACE_ADDR
> USB	192.168.42.1
> BlueTooth	192.168.44.1
测试成功，感谢作者及时更新！
