### ISSUE TITLE
请问一下开发者1.050版能在a13的miui14上用吗？

### ISSUE THREAD

**Issue by tianminyzy** [XhyEax/SoftApHelper#13]

**Comment by XhyEax** [comment]
未测试，理论上可用.
（~你试一下不就知道了~）

**Comment by zimq** [comment]
我同系统用不了，你能用吗

**Comment by tianminyzy** [comment]
![Screenshot_2023-07-23-15-29-55-644_com.android.shell.jpg](https://github.com/XhyEax/SoftApHelper/assets/45175519/26f6a19e-9f7f-4e29-8f8b-d640f34ca7cf)
我勾了这三个，重启可用，至于你说的几分钟就失效或许是和别的模块冲突

**Comment by zimq** [comment]
我好像没开网络相关的模块，你有用米客吗

**Comment by tianminyzy** [comment]
没












holyshin
***@***.***


---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年7月23日(周日) 下午4:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 请问一下开发者1.050版能在a13的miui14上用吗？ (Issue #13)




 
我好像没开网络相关的模块，你有用米客吗
