### ISSUE TITLE
是否支持以太网共享

### ISSUE THREAD

**Issue by Githubsanae** [XhyEax/SoftApHelper#14]
设备:s20
系统:安卓13（oneui5.1）
问题:只可固定usb共享和热点网段，以太网共享（通过typec转网口共享路由器）无法固定网段。

**Comment by XhyEax** [comment]
待会我更新一下，然后你测一下



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年5月21日(周日) 中午12:54
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 是否支持以太网共享 (Issue #14)




 
设备:s20
 系统:安卓13（oneui5.1）
 问题:只可固定usb共享和热点网段，以太网共享（通过typec转网口共享路由器）无法固定网段。

**Comment by XhyEax** [comment]
[v1.060](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.060)

**Comment by Githubsanae** [comment]
谢谢，以太网成功固定192.168.50.1/24网段
