### ISSUE TITLE
用最新版固定usbip有问题

### ISSUE THREAD

**Issue by JimmyPOon1** [XhyEax/SoftApHelper#15]
[TetheringGoogle.zip](https://github.com/XhyEax/SoftApHelper/files/11588479/TetheringGoogle.zip)

**Comment by JimmyPOon1** [comment]
我用最新版固定usbip 共享给路由器使用  热点机网络正常 但是 其他链接路由器手机会经常没网  必须重新开关usb共享   手机是真我  系统是11但是里面包含一些12

**Comment by XhyEax** [comment]
使用usb共享，给电脑使用，然后电脑开自动热点呢
