### ISSUE TITLE
miui14 Android13无效

### ISSUE THREAD

**Issue by zimq** [XhyEax/SoftApHelper#16]
[privapps.zip](https://github.com/XhyEax/SoftApHelper/files/12138148/privapps.zip)

**Comment by XhyEax** [comment]
192.168.1.1版本呢

**Comment by XhyEax** [comment]
反编译看了下，是安卓13的官方代码。理论上应该没问题。
作用域都选了吗？

**Comment by zimq** [comment]
> 192.168.1.1版本呢

先试的这个，两个都无效

**Comment by zimq** [comment]
> 反编译看了下，是安卓13的官方代码。理论上应该没问题。 作用域都选了吗？
包名里有network的只有tethering和网络管理器(com.android.networkstack.inprocess)两个,都选了，系统框架也选了
![new ducument](https://github.com/XhyEax/SoftApHelper/assets/11613075/483964fb-b957-48cf-9348-328474d1378c)

**Comment by zimq** [comment]
上一个版本刚开机的时候好像还会固定ip1.1几分钟

**Comment by XhyEax** [comment]
插件版本：v1.060
系统：miui14 Android13
作用域只勾选系统框架，亲测可用。

大概率是模块冲突，把其他magisk、xposed模块禁用再试试呢

**Comment by zimq** [comment]
> 插件版本：v1.060 系统：miui14 Android13 作用域只勾选系统框架，亲测可用。
> 
> 大概率是模块冲突，把其他magisk、xposed模块禁用再试试呢

全关了只保留一个还是不行
![Screenshot_2023-07-23-22-00-07-828_utyubh g quddpt](https://github.com/XhyEax/SoftApHelper/assets/11613075/076c32a9-0d65-4e85-bbd9-8fcbefeb70f2)
![Screenshot_2023-07-23-21-59-47-567_com android shell](https://github.com/XhyEax/SoftApHelper/assets/11613075/347b0f55-81a6-42a6-8e54-a1e07fd33877)
![Screenshot_2023-07-23-22-08-00-396_com android settings](https://github.com/XhyEax/SoftApHelper/assets/11613075/3e13a297-32f7-4b17-886a-30e08ec1a0b6)

**Comment by XhyEax** [comment]
不是在这看ip，命令行执行ifconfig，看inet addr

**Comment by XhyEax** [comment]
不是在这看ip。
adb shell后，执行ifconfig，看inet addr。

**Comment by XhyEax** [comment]
可以手机开个http服务，然后电脑看能不能连上。
比如：[https://www.coolapk.com/apk/app.eleven.com.fastfiletransfer](https://www.coolapk.com/apk/app.eleven.com.fastfiletransfer)

**Comment by zimq** [comment]
> 可以手机开个http服务，然后电脑看能不能连上。 比如：https://www.coolapk.com/apk/app.eleven.com.fastfiletransfer

这个app好像是1.1，不能获得一个固定的无线调试地址吗，我之前在旧手机上miui13Android12，好像无线调试的地址也是1.1

**Comment by zimq** [comment]
> 不是在这看ip。 adb shell后，执行ifconfig，看inet addr。

你说的是wlan2的inet addr吗，一些软件和设置读的似乎是rmnet_data3的inet addr，我主要是想用alist和无效调试，在旧手机上是1.1
![屏幕截图_20221023_210010](https://github.com/XhyEax/SoftApHelper/assets/11613075/dfb20766-3f59-486d-9ccb-0c4216441094)

**Comment by zimq** [comment]
> 不是在这看ip。 adb shell后，执行ifconfig，看inet addr。

你说的是wlan2的inet addr吗，一些软件和设置读的似乎是rmnet_data3的inet addr，我主要是想用alist和无效调试，在旧手机上是1.1
![image](https://github.com/XhyEax/SoftApHelper/assets/11613075/a51fd2e7-ced5-45fa-9680-02d064e32b7c)

**Comment by XhyEax** [comment]
用这个开无线调试
[https://www.coolapk.com/apk/com.rair.adbwifi](https://www.coolapk.com/apk/com.rair.adbwifi)
然后直接adb connect 192.168.1.1就行，不用管显示的ip，关键看能不能用

**Comment by XhyEax** [comment]
> > 可以手机开个http服务，然后电脑看能不能连上。 比如：https://www.coolapk.com/apk/app.eleven.com.fastfiletransfer
> 
> 这个app好像是1.1，不能获得一个固定的无线调试地址吗，我之前在旧手机上miui13Android12，好像无线调试的地址也是1.1

那说明插件实际上是生效的，别看显示ip，直接看能不能连接。

**Comment by zimq** [comment]
> 用这个开无线调试 https://www.coolapk.com/apk/com.rair.adbwifi 然后直接adb connect 192.168.1.1就行，不用管显示的ip，关键看能不能用

这个能用

**Comment by zimq** [comment]
> > > 可以手机开个http服务，然后电脑看能不能连上。 比如：https://www.coolapk.com/apk/app.eleven.com.fastfiletransfer
> > 
> > 
> > 这个app好像是1.1，不能获得一个固定的无线调试地址吗，我之前在旧手机上miui13Android12，好像无线调试的地址也是1.1
> 
> 那说明插件实际上是生效的，别看显示ip，直接看能不能连接。

alist也能用，同一个设备既然有a类和c类两个地址，两个地址都能用，wlan2是一个子网？

**Comment by XhyEax** [comment]
> 

设备有多张网卡，一般应用监听的是所有网卡的本机ip。

**Comment by zimq** [comment]
> > 
> 
> 设备有多张网卡，一般应用监听的是所有网卡的本机ip。

可能，好像现在的手机都是双模WiFi，可以同时连WiFi和开热点，不同的应用选择显示的AP不同
