### ISSUE TITLE
lsp管理器无法勾选tethering

### ISSUE THREAD

**Issue by blplb** [XhyEax/SoftApHelper#17]
在管理器勾选tethering后，无论是返回模块列表还是进入SoftApHelper再查看勾选列表tethering都没有勾选，但是经过测试，模块生效了
![Screenshot_2023-09-29-02-43-34-096_com android shell](https://github.com/XhyEax/SoftApHelper/assets/107800306/f6468367-6b1e-4dd1-bf54-36e57c08ff59)
![Screenshot_2023-09-29-02-43-31-286_com xhy xp softaphelper](https://github.com/XhyEax/SoftApHelper/assets/107800306/57796037-2cfd-49be-b5c3-1ae5bf974844)
![Screenshot_2023-09-29-02-43-19-770_com termux](https://github.com/XhyEax/SoftApHelper/assets/107800306/9185a235-6bed-46e0-8a63-c86dc1e4603f)

**Comment by XhyEax** [comment]
安卓13一般只勾选系统框架就可以生效了。加Tethering是保险起见。


然后这种显示问题应该找LSPosed反馈吧。


我这边安卓13+LSPosed1.8.6没遇到这个问题。

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月29日(周五) 凌晨2:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] lsp管理器无法勾选tethering (Issue #17)




 
在管理器勾选tethering后，无论是返回模块列表还是进入SoftApHelper再查看勾选列表tethering都没有勾选，但是经过测试，模块生效了

**Comment by XhyEax** [comment]
试了下LSPosed1.9.1，出现了跟你相同的显示问题。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年9月29日(周五) 凌晨2:52
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] lsp管理器无法勾选tethering (Issue #17)




 
在管理器勾选tethering后，无论是返回模块列表还是进入SoftApHelper再查看勾选列表tethering都没有勾选，但是经过测试，模块生效了

**Comment by XhyEax** [comment]
重启后再次打开LSPosed，发现被勾上了。
