### ISSUE TITLE
功能建议

### ISSUE THREAD

**Issue by sushen339** [XhyEax/SoftApHelper#18]
首先感谢开发者的贡献，能让我们方便使用热点。

我希望能增加一个固定信道的功能。
因为
“某些国家/地区存在监管限制，不允许热点自行在 5 GHz 频段上运行。只有当 Windows® 10 电脑连接至位于特定（被动）的 5GHz 通道上的无线接入点 （AP） 时，您才能在 5GHz 上使用热点。

这种表现是预料之中的，由于存在特定国家的监管限制。
但是，对于这些国家/地区，您可以先连接至获批准的 5GHz（被动）通道，然后再启动热点，来使用 5GHz 上的热点。”

手机5g热点支持36,​40,​44,​48,​52,​56,​60,​64,​149,​153,​157,​161,​165信道，但是电脑只有连接到149, 153, 157, 161 或 165频段时才能启动5g热点。

手机启动热点时信道是随机的，希望能固定到一个信道，例如149，这样子将会方便很多。

大佬如果有时间可以看看

**Comment by XhyEax** [comment]
安卓版本号是多少



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月29日(周五) 下午3:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 功能建议 (Issue #18)




 
首先感谢开发者的贡献，能让我们方便使用热点。
 
我希望能增加一个固定信道的功能。
 因为
 “某些国家/地区存在监管限制，不允许热点自行在 5 GHz 频段上运行。只有当 Windows® 10 电脑连接至位于特定（被动）的 5GHz 通道上的无线接入点 （AP） 时，您才能在 5GHz 上使用热点。
 
这种表现是预料之中的，由于存在特定国家的监管限制。
 但是，对于这些国家/地区，您可以先连接至获批准的 5GHz（被动）通道，然后再启动热点，来使用 5GHz 上的热点。”
 
手机5g热点支持36,​40,​44,​48,​52,​56,​60,​64,​149,​153,​157,​161,​165频段，但是电脑只有连接到149, 153, 157, 161 或 165频段时才能启动5g热点。
 
手机启动热点时频段是随机的，希望能固定到一个频段，例如149，这样子将会方便很多。
 
大佬如果有时间可以看看

**Comment by XhyEax** [comment]
手机和电脑设置成同一个国家区域，应该就可以解决了。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年12月29日(周五) 下午3:26
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 功能建议 (Issue #18)




 
首先感谢开发者的贡献，能让我们方便使用热点。
 
我希望能增加一个固定信道的功能。
 因为
 “某些国家/地区存在监管限制，不允许热点自行在 5 GHz 频段上运行。只有当 Windows® 10 电脑连接至位于特定（被动）的 5GHz 通道上的无线接入点 （AP） 时，您才能在 5GHz 上使用热点。
 
这种表现是预料之中的，由于存在特定国家的监管限制。
 但是，对于这些国家/地区，您可以先连接至获批准的 5GHz（被动）通道，然后再启动热点，来使用 5GHz 上的热点。”
 
手机5g热点支持36,​40,​44,​48,​52,​56,​60,​64,​149,​153,​157,​161,​165频段，但是电脑只有连接到149, 153, 157, 161 或 165频段时才能启动5g热点。
 
手机启动热点时频段是随机的，希望能固定到一个频段，例如149，这样子将会方便很多。
 
大佬如果有时间可以看看

**Comment by XhyEax** [comment]
在安卓12以上，可以通过adb shell cmd wifi start-softap命令指定信道。

**Comment by XhyEax** [comment]
5g信道转频率公式：5160 + (channel - 32) * 5

**Comment by sushen339** [comment]
感谢大佬的回复，是安卓13的系统。
手机和电脑设置区域都是中国，但是Windows限制了只有在连接了149、153、157、161 、165时才能开启5g热点。
有root情况下用“vpn热点”这个软件也能调整信道，但每次启动都要设置一遍，属实不够方便和优雅。
如果能用这插件实现这个功能，那就太棒了

**Comment by XhyEax** [comment]
你vx多少，我加你

**Comment by sushen339** [comment]
q2447684188

**Comment by XhyEax** [comment]
## 固定5G热点信道
### 方法1：使用本插件
（TODO）安卓12以下：指定AP频段为特定信道。
安卓13+：如果开启5G热点时，未指定5G信道(单个channel或者allowedAcsChannels)，锁定频段为`149,153,157,161,165`，频宽为`320MHZ`(受硬件限制，实际可能只有80MHZ)。

### 方法2：使用VPNHotspot
使用[VPNHotspot](https://github.com/Mygod/VPNHotspot)设置系统热点配置。
安卓12以下：指定AP频段为特定信道。
安卓13+：指定频段为5G，ACS可选频段为信道，或指定AP频段为特定信道。
手机重启后可能需要手动指定。
