### ISSUE TITLE
p2p0 tunnel can't get static ipv4 address

### ISSUE THREAD

**Issue by kuragege** [XhyEax/SoftApHelper#19]
The wireless repeater function of vpnhotspot can not get static ipv4 address by this xposed module, this tunnel(p2p0) seemed like to be different from the ap tunnel(wlan). By the way, after i activated this module, the adb connection appeared to be not working properly. Can you help me troubleshoot the issue?

**Comment by kuragege** [comment]
If you are simultaneously using a VPN, there will be three network gateways: tun0, wlan, and p2p0. In terms of priority, wlan < tun0 < p2p0.

**Comment by XhyEax** [comment]
What is your Android version? And how to reproduct the issue?



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 10, 2024 00:20 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [XhyEax/SoftApHelper] p2p0 tunnel can't get static ipv4 address(Issue #19)




 
The wireless repeater function of vpnhotspot can not get static ipv4 address by this xposed module, this tunnel seemed like to be different from the ap tunnel. By the way, after i avtivated this module, the adb connection appeared to be not working properly. Can you help me troubleshoot the issue?

**Comment by XhyEax** [comment]
Wifi adb or USB adb?



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 10, 2024 00:20 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [XhyEax/SoftApHelper] p2p0 tunnel can't get static ipv4 address(Issue #19)




 
The wireless repeater function of vpnhotspot can not get static ipv4 address by this xposed module, this tunnel seemed like to be different from the ap tunnel. By the way, after i avtivated this module, the adb connection appeared to be not working properly. Can you help me troubleshoot the issue?

**Comment by kuragege** [comment]
![image](https://github.com/XhyEax/SoftApHelper/assets/115913311/596e5b67-0350-4592-972a-9cdc8b52d5b7)
wifi adb
android version:11 device:lubancat1
开启模块后 临时wifi热点以及wifi热点ip地址是固定的，但是无线中继模式依然是随机ip

**Comment by XhyEax** [comment]
无线中继属于预期内现象，为避免与中继节点冲突。



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 10, 2024 12:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XhyEax/SoftApHelper] p2p0 tunnel can't get static ipv4 address(Issue #19)




 
image.png (view on web)
 wifi adb
 android version:11 device:lubancat1
 开启模块后 临时wifi热点以及wifi热点ip地址是固定的，但是无线中继模式依然是随机ip

**Comment by XhyEax** [comment]
我这边开启模块后，adb是正常的



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 10, 2024 00:20 AM
To: ***@***.***&gt;;
Cc: ***@***.***&gt;;
Subject: [XhyEax/SoftApHelper] p2p0 tunnel can't get static ipv4 address(Issue #19)




 
The wireless repeater function of vpnhotspot can not get static ipv4 address by this xposed module, this tunnel seemed like to be different from the ap tunnel. By the way, after i avtivated this module, the adb connection appeared to be not working properly. Can you help me troubleshoot the issue?

**Comment by kuragege** [comment]
adb不成功可能是偶然性的原因，因为开发板没有外接屏幕，测试起来不太方便，那无线中继的问题可以解决吗，因为这个设备不支持在连接wlan的情况下开启热点

**Comment by XhyEax** [comment]
wifi adb的同时，是怎么开的？vpn热点+无线中继？



---Original---
From: ***@***.***&gt;
Date: Wed, Jan 10, 2024 12:22 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XhyEax/SoftApHelper] p2p0 tunnel can't get static ipv4 address(Issue #19)




 
image.png (view on web)
 wifi adb
 android version:11 device:lubancat1
 开启模块后 临时wifi热点以及wifi热点ip地址是固定的，但是无线中继模式依然是随机ip

**Comment by kuragege** [comment]
![image](https://github.com/XhyEax/SoftApHelper/assets/115913311/bd04d108-787d-4244-9c67-8f6d6e0cb5a7)

wifi adb是借助 谷歌商店中的wadb实现的，连接的是vpn热点无线中继模式开启的p2p0的通道，希望这个模块能把p2p0这个通道的ip地址固定下，在android10当中，这个通道的ip被固定为192.168.49.1/24

**Comment by XhyEax** [comment]
[v1.080](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.080)开始，p2p0固定为192.168.49.1。
