### ISSUE TITLE
作为热点机必备插件希望增加新功能

### ISSUE THREAD

**Issue by AXEVO** [XhyEax/SoftApHelper#20]
让本机的软件认为本机正在连接WiFi，避免总是弹出烦人的正在使用流量提示
让本机开出来的WiFi热点标记为普通路由器而不是移动热点，避免连上这个热点的设备将其识别为热点导致自动更新 自动同步等功能无法使用

**Comment by XhyEax** [comment]
1. “本机联网状态修改”此功能已有插件，自行搜索。

每个app检测联网状态的方式不同，都需要进行适配。
为避免重复造轮子，该功能不在后续开发计划中。


2. “WiFi热点标记为普通路由器”，该功能理论上可以实现。（去除DHCP的Option字段ANDROID_METERED）


“隐藏热点类型”功能，新版已发。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月31日(周日) 下午2:21
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 作为热点机必备插件希望增加新功能 (Issue #20)




 
让本机的软件认为本机正在连接WiFi，避免总是弹出烦人的正在使用流量提示
 让本机开出来的WiFi热点标记为普通路由器而不是移动热点，避免连上这个热点的设备将其识别为热点导致自动更新 自动同步等功能无法使用

**Comment by XhyEax** [comment]
安卓10+支持“隐藏热点类型”。

[v1.090](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.090)
