### ISSUE TITLE
安卓13，即使用VPN HOTSPOT指定了5g信道36,40,44,还是会被指定为149以上信道。

### ISSUE THREAD

**Issue by silverblade7246** [XhyEax/SoftApHelper#21]
安卓13，即使用VPN HOTSPOT指定了5g信道36,40,44,开启模块后5g热点的信道还是会被指定为149以上信道。

**Comment by XhyEax** [comment]
不开模块呢？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年3月31日(周日) 晚上6:55
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 安卓13，即使用VPN HOTSPOT指定了5g信道36,40,44,还是会被指定为149以上信道。 (Issue #21)




 
安卓13，即使用VPN HOTSPOT指定了5g信道36,40,44,开启模块后5g热点的信道还是会被指定为149以上信道。

**Comment by silverblade7246** [comment]
> 不开模块呢？
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年3月31日(周日) 晚上6:55 收件人: ***@***.***&gt;; 抄送: ***@***.***&gt;; 主题: [XhyEax/SoftApHelper] 安卓13，即使用VPN HOTSPOT指定了5g信道36,40,44,还是会被指定为149以上信道。 (Issue #21) 安卓13，即使用VPN HOTSPOT指定了5g信道36,40,44,开启模块后5g热点的信道还是会被指定为149以上信道。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you are subscribed to this thread.Message ID: ***@***.***&gt;

不开模块可以用VPN HOSTSPOT指定信道，我刚刚试着下了1.6版本的SoftApHelper解决了，这个版本可以固定IP同时我也能使用VPN HOTSPOT指定信道。

**Comment by XhyEax** [comment]
想问下为啥会有使用 5g信道36,40,44 的需求

**Comment by XhyEax** [comment]
我自己的手机关闭模块后，也指定不了36,40,44信道，可能是硬件不支持。
所以是你的设备只支持低信道？

**Comment by silverblade7246** [comment]
日版游戏机不设置这些信道无法搜索到热点😭

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by XhyEax** [comment]
发了新版。[v1.091](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.091)
你试试用VPN热点，能不能指定到低频段。

**Comment by XhyEax** [comment]
现在只有当`5 GHz ACS 可选频段`为空时，才修改成高频段。

**Comment by silverblade7246** [comment]
可以

获取Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
