### ISSUE TITLE
热点类型问题

### ISSUE THREAD

**Issue by umiiiia** [XhyEax/SoftApHelper#22]
作者您好，请问可以增加模拟标准Wi-Fi吗？Android13，aosp系统 ，谢谢🌹

**Comment by XhyEax** [comment]
最新版已实现该功能，其他设备不会识别为热点。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月12日(周五) 晚上11:11
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 热点类型问题 (Issue #22)




 
作者您好，请问可以增加模拟标准Wi-Fi吗？Android13，aosp系统 ，谢谢🌹

**Comment by umiiiia** [comment]
辛苦您啦，我再试试
