### ISSUE TITLE
小米手机安装后不显示app无法进入应用

### ISSUE THREAD

**Issue by INSIinc** [XhyEax/SoftApHelper#23]

**Comment by XhyEax** [comment]
Xposed模块，默认不显示系统图标。查看功能是否可用即可。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年4月21日(周日) 晚上9:18
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 小米手机安装后不显示app无法进入应用 (Issue #23)

**Comment by INSIinc** [comment]
红米k50安装后，ubuntu连接热点无法ping通192.168.1.1或192.168.43.1

**Comment by INSIinc** [comment]
![Uploading IMG_20240421_225811.jpg…]()

**Comment by XhyEax** [comment]
开启热点后，手机端使用ifconfig命令查看IP（或usb连接电脑后，进入adb shell执行）

**Comment by XhyEax** [comment]
> 红米k50安装后，ubuntu连接热点无法ping通192.168.1.1或192.168.43.1

两个版本都尝试了？

**Comment by XhyEax** [comment]
安卓版本多少？LSPosed中勾选系统框架，然后重启

**Comment by INSIinc** [comment]
![1e21b4fd4f12871f5a1cc33dbff444c7](https://github.com/XhyEax/SoftApHelper/assets/42080694/b5dfdc9a-3bb1-4f7c-9d1b-0c9837ad2b8c)
![d4a0a4a3b3a24693b6443840fb740891](https://github.com/XhyEax/SoftApHelper/assets/42080694/b5036baf-07b7-4509-ad2d-c312bb02fec5)

**Comment by XhyEax** [comment]
你这Xposed环境都没装。
安卓13解锁bootloader后，使用LSPosed框架。自行搜索教程。
