### ISSUE TITLE
固定USB共享MAC地址

### ISSUE THREAD

**Issue by dysf888** [XhyEax/SoftApHelper#24]
貌似是 InterfaceParams中的getMacAddress
插在ikuai上拔插一下mac变动就会导致接口绑定异常。

**Comment by XhyEax** [comment]
确实每次重新开启wifi或者usb热点后，手里的mac地址会变。
有空看看。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年5月21日(周二) 下午4:19
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 固定USB共享MAC地址 (Issue #24)




 
貌似是 InterfaceParams中的getMacAddress
 插在ikuai上拔插一下mac变动就会导致接口绑定异常。

**Comment by dysf888** [comment]
不是的，保持拔插USB后不变就行，有时候接口会松动

Xhy ***@***.***>于2024年5月22日 周三23:27写道：

**Comment by XhyEax** [comment]
[system/netd/server/InterfaceController.cpp](http://aospxref.com/android-14.0.0_r2/xref/system/netd/server/InterfaceController.cpp#440)
InterfaceController的代码实现中不包含指定hwAddr的功能。

**Comment by XhyEax** [comment]
只能选择换一根更牢固的数据线了。

**Comment by XhyEax** [comment]
你所提到的InterfaceParams主要是用于获取上游interface的配置，并不能修改自己的mac地址。

**Comment by dysf888** [comment]
> 你所提到的InterfaceParams主要是用于获取上游interface的配置，并不能修改自己的mac地址。

http://aospxref.com/android-12.0.0_r3/xref/packages/modules/Connectivity/Tethering/src/com/android/networkstack/tethering/Tethering.java#1356
