### ISSUE TITLE
能不能出个可以自定义热点网段的版本？

### ISSUE THREAD

**Issue by zyf950317** [XhyEax/SoftApHelper#27]
192.168.43.0/24和192.168.1.0/24都有可能和上层网关冲突，能否出个可以自定义网段的版本呢？

**Comment by zyf950317** [comment]
用MT管理器编译dex把所有192.168.43.1替换成想换的IP再安装可以解决，不过如果开发者能给模块内置个自定义功能就更好了，这样对于小白来说操作也方便点

**Comment by XhyEax** [comment]
由于涉及配置保存，需要适配不同的安卓系统版本(系统层面限制)以及Xposed版本(API)，时间成本较高，该功能暂不考虑开发。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年9月30日(周一) 晚上8:16
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 能不能出个可以自定义热点网段的版本？ (Issue #27)




 
用MT管理器编译dex把所有192.168.43.1替换成想换的IP再安装可以解决，不过如果开发者能给模块内置个自定义功能就更好了，这样对于小白来说操作也方便点

**Comment by zhugunzi** [comment]
安卓14 不起作用

**Comment by XhyEax** [comment]
> 安卓14 不起作用

安卓14已知问题：
部分安卓14系统由于存在缓存，需要手动重新优化Tethering，模块才能生效

LSPosed-模块-SoftApHelper-长按Tethering-重新优化-重启手机

[图片示例](https://xhy-1252675344.cos.ap-beijing.myqcloud.com/imgs/softap-redex.jpg)
