### ISSUE TITLE
Samsung Invalid plug-in.

### ISSUE THREAD

**Issue by Ran-Xing** [XhyEax/SoftApHelper#28]
Android 14
One UI 6.1
If there is private information in the log, please delete it for me.

[full.log](https://github.com/user-attachments/files/17083703/full.log)
![90A89847-D324-4697-8D37-87CEFC12E001](https://github.com/user-attachments/assets/20d93f2e-f695-43fe-b628-72773340ac92)
![6A764CF5-5A91-441B-91A0-E61A78C058D0](https://github.com/user-attachments/assets/dd733fe8-b41f-4d96-9cee-ca41605a6d8f)
![ECEE2721-D294-4360-95C0-2491AF60F615](https://github.com/user-attachments/assets/9d45cbea-5771-4c12-ae9f-f7a214579c8a)

**Comment by XhyEax** [comment]
adb shell或者termux执行ifconfig，看看ip变化没有

**Comment by XhyEax** [comment]
可以先升级系统版本试试

**Comment by Ran-Xing** [comment]
@XhyEax 我直接连接热点，网段是随机的，系统算蛮新的

**Comment by Ran-Xing** [comment]
还有没有什么关键字呢。

**Comment by XhyEax** [comment]
执行ifconfig查看本机ip，或者其他手机连接热点后截图发一下。



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 21, 2024 20:19 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XhyEax/SoftApHelper] Samsung Invalid plug-in. (Issue #28)




 
@XhyEax 我直接连接热点，网段是随机的，系统算蛮新的

**Comment by Ran-Xing** [comment]
![D3760CF3-B20B-4CB7-A51E-E472103C04EB](https://github.com/user-attachments/assets/77fb4398-b6d5-479c-a476-bb40a4356c76)

![509A9C07-4EC5-484A-8B1E-B2FC84E7EBD7](https://github.com/user-attachments/assets/79e9517f-943e-49a7-96cc-ac294e314db3)

**Comment by XhyEax** [comment]
试试1.1版本能用不



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 21, 2024 22:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XhyEax/SoftApHelper] Samsung Invalid plug-in. (Issue #28)




 
D3760CF3-B20B-4CB7-A51E-E472103C04EB.jpeg (view on web)
 
509A9C07-4EC5-484A-8B1E-B2FC84E7EBD7.jpeg (view on web)

**Comment by Ran-Xing** [comment]
@XhyEax 试过了，不得行，哈哈哈，你说的应该是ip 192.168.1.1吧，不是版本1.1吧，我看没有1.1版本

**Comment by XhyEax** [comment]
那估计就是系统不适配了



---Original---
From: ***@***.***&gt;
Date: Sat, Sep 21, 2024 22:29 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XhyEax/SoftApHelper] Samsung Invalid plug-in. (Issue #28)




 
@XhyEax 试过了，不得行，哈哈哈，你说的应该是ip 192.168.1.1吧，不是版本1.1吧，我看没有1.1版本

**Comment by XhyEax** [comment]
降级系统版本应该可以使用

**Comment by Ran-Xing** [comment]
我挨个试过了，都不行，哈哈哈

**Comment by zhugunzi** [comment]
我是 moto razr2022 安卓14 也不行

**Comment by zhugunzi** [comment]
大佬加油啊

**Comment by XhyEax** [comment]
系统不适配导致的，手头没有三星和摩托罗拉的手机，无法测试。


目前推测是作用域问题或系统代码问题，
请上传/apex/com.android.tethering/priv-app/下的apk到网盘，帮助排查问题。


其他解决方法：建议降级到安卓13系统版本，或更换其他第三方系统(最新版LineageOS 21 测试可用)。



---Original---
From: ***@***.***&gt;
Date: Thu, Oct 10, 2024 14:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [XhyEax/SoftApHelper] Samsung Invalid plug-in. (Issue #28)




 
我是 moto razr2022 安卓14 也不行

**Comment by Ran-Xing** [comment]
三星有个等级控制，目前最新的是8，8里面有好几个版本，这些版本之间才能互相刷，所以降不了Android13

**Comment by zhugunzi** [comment]
![priv-app](https://github.com/user-attachments/assets/7ddefcea-f261-42af-95c9-d65ed32f4f08)
这是priv_app目录把jpg改成zip就可以了

**Comment by zhugunzi** [comment]
[priv-app.zip](https://github.com/user-attachments/files/17352648/priv-app.zip)
不好意 用这个吧！刚开始以为无法直接上传

**Comment by Ran-Xing** [comment]
@XhyEax 大佬，我这已经锁了bl，暂时没有已root的机器，我从刷机包里面解出来了一个apex文件可以吗？路径是 /system/apex/com.google.android.tethering_compressed.apex

**Comment by Ran-Xing** [comment]
文件下载：[samsung android 14.zip](https://github.com/user-attachments/files/17354737/samsung.android.14.zip)
固件下载：
1. 访问 https://samfw.com/firmware/SM-F721B/THL/F721BXXU8GXH9
2. 搜索
AP_F721BXXU8GXH9_F721BXXU8GXH9_MQB84892640_REV00_user_low_ship_MULTI_CERT_meta_OS14.tar.md5.zip
3.  点击 Download
4.  点击 Download SamFw server

固件解压：

1. https://cxxsheng.com/2024/09/27/%E8%A7%A3%E5%8C%85%E4%B8%89%E6%98%9F%E5%88%B7%E6%9C%BA%E5%8C%85%E4%B8%AD%E7%9A%84system-img%EF%BC%88Mac-OS%E7%89%88%E6%9C%AC%EF%BC%89/
2. https://mintimate.cn/2020/08/10/androidReverseSystem/

经过测试文件格式 F2FS 需要用能root的虚拟机来挂载，或者Linux

**Comment by Ran-Xing** [comment]
cd /sdcard/Download/
for file in *.img
do
	echo "$file"
    mkdir "/data/local/tmp/$file"
    mount -ro loop "/sdcard/Download/$file" "/data/local/tmp/$file"
done
cd /data/local/tmp/
find ./ -name "*tethering*"



for file in *.lz4
do
    lz4 -d "$file"
done

**Comment by XhyEax** [comment]
> @XhyEax 大佬，我这已经锁了bl，暂时没有已root的机器，我从刷机包里面解出来了一个apex文件可以吗？路径是 /system/apex/com.google.android.tethering_compressed.apex

只要能把TetheringGoogle.apk 解压出来就行

**Comment by XhyEax** [comment]
> [priv-app.zip](https://github.com/user-attachments/files/17352648/priv-app.zip) 不好意 用这个吧！刚开始以为无法直接上传

我反编译看了，代码跟aosp没区别，不知道为什么hook不上。

**Comment by XhyEax** [comment]
> ```shell
> cd /sdcard/Download/
> for file in *.img
> do
> 	echo "$file"
>     mkdir "/data/local/tmp/$file"
>     mount -ro loop "/sdcard/Download/$file" "/data/local/tmp/$file"
> done
> cd /data/local/tmp/
> find ./ -name "*tethering*"
> 
> 
> 
> for file in *.lz4
> do
>     lz4 -d "$file"
> done
> ```

你倒是把文件传上来啊。。。

**Comment by Ran-Xing** [comment]
我就是因为找不到，所以才把能用的贴上来了

**Comment by XhyEax** [comment]
> [priv-app.zip](https://github.com/user-attachments/files/17352648/priv-app.zip) 不好意 用这个吧！刚开始以为无法直接上传

微信加我: xhyeax。我发你个带日志的版本，然后你把日志发我。

**Comment by XhyEax** [comment]
> 我就是因为找不到，所以才把能用的贴上来了

行吧，那意思是你目前回锁bl，也不用这个插件了。

**Comment by XhyEax** [comment]
> 我就是因为找不到，所以才把能用的贴上来了

这个问题需要联合调试才能定位。既然你现在都不用这个了，我再去分析也没太大意义。

**Comment by zhugunzi** [comment]
> > [priv-app.zip](https://github.com/user-attachments/files/17352648/priv-app.zip) 不好意 用这个吧！刚开始以为无法直接上传
> 
> 我反编译看了，代码跟aosp没区别，不知道为什么hook不上。

大佬我有2个一样的手机一样的安卓14系统 magisk和lposed 版本也一样，但第二个手机 直接装的192.168.1.1版本直接就成功了，前面一个手机好像是先装了192.168.1.42的后面在回退折腾了好久还是不行，是不是安装后哪里有缓存卸载也删不掉导致的

**Comment by XhyEax** [comment]
部分安卓14系统需要手动**重新优化Tethering**，模块才能生效

LSPosed-模块-SoftApHelper-长按Tethering-重新优化-重启手机

![](https://xhy-1252675344.cos.ap-beijing.myqcloud.com/imgs/softap-redex.jpg)

**Comment by XhyEax** [comment]
安卓14系统原因导致，手动重新优化目标APP后，可正常Hook。
