### ISSUE TITLE
可不可以出个可以自定义固定热点mac地址

### ISSUE THREAD

**Issue by Wpenga** [XhyEax/SoftApHelper#29]
已知每次开启热点，会生成wlan2相应配置文件，mac地址在address文件里，但我无法直接修改，是因为进程在使用中吧。
/sys/class/net/wlan2/address

aa:e9:c2:f7:6a:cc

是否有什么思路可以固定

使用小米14

**Comment by XhyEax** [comment]
意思是正常情况下每次开热点，BSSID会变化？

**Comment by XhyEax** [comment]
通过Hook SoftApConfiguration构造函数的第二个参数可以解决。没空加配置自定义功能。

可以使用[VPNHotspot](https://github.com/Mygod/VPNHotspot)设置系统热点配置（右上角-WLAN热点-高级接入点设置-持久化随机MAC地址）。

**Comment by XhyEax** [comment]
上传了Android13+：固定BSSID版本，MAC地址为`aa:bb:cc:dd:ee:ff`
[https://github.com/XhyEax/SoftApHelper/releases/tag/v1.091](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.091)
