### ISSUE TITLE
[bug] Does not work on my device

### ISSUE THREAD

**Issue by BlacK201** [XhyEax/SoftApHelper#4]
Device: Redmi K40
Magisk Version: 25.2
LSPosed Version: 1.8.3

Enabled this module and selected the "System Framework" app.
After restarted, I still got a random IP when I open the AP.

**Comment by itouakirai** [comment]
Device: Redmi K40
system:pep12
Magisk Version: 24.3
LSPosed Version: 1.8.3

same
After the software is opened it shows a white screen and does not work

**Comment by XhyEax** [comment]
不好意思，Android 12设备未经测试。
可能需要自行定位目标包名进行修复。
或者尝试最新合并的版本。

Sorry, I didn't test this module for Android 12.
Maybe you need to fix it by find target package name manually.
Or try the latest version merged.

**Comment by BlacK201** [comment]
好的，我现在尝试一下，谢谢！
~~btw，大佬好肝 这个点都还没睡~~

**Comment by XhyEax** [comment]
因为之前Epic Games的reply-all事件，就把github的邮件推送关了，没想到积累了这么久的issue。
根据提交的pr，可能是包名不对，可以自己编译，打日志看看。

**Comment by BlacK201** [comment]
现在它正常工作了，谢谢！

**Comment by JimmyPOon1** [comment]
你是怎么解决的啊
