### ISSUE TITLE
启动白屏且固定网关ip功能无效

### ISSUE THREAD

**Issue by itouakirai** [XhyEax/SoftApHelper#6]
设备redmi k40
系统pep12
白屏界面如下
![photo_2022-09-03_14-45-18](https://user-images.githubusercontent.com/85016486/188259255-dd7d31d0-7c29-4f2a-98aa-471398ac41e6.jpg)

lsp版本18.3
lsp日志如下
[LSPosed_2022-09-03T14_26_19.108.zip](https://github.com/XhyEax/SoftApHelper/files/9481946/LSPosed_2022-09-03T14_26_19.108.zip)

**Comment by dsfgdadg** [comment]
这个没有设置界面，lsp中勾选好作用域就行

**Comment by dsfgdadg** [comment]
我提交pr了，作者还没合并。
你可以编译这个仓库的试试，有一点点改动，https://github.com/dsfgdadg/SoftApHelper

**Comment by XhyEax** [comment]
白屏是正常的，主页并未添加任何显示。
由于手头没有Android 12设备，目标包名可能不对。
已合并楼上的pr，可以试试。

**Comment by XhyEax** [comment]
已发布到Release页，并提供不过滤包名版本。
可以测试一下。

**Comment by itouakirai** [comment]
新版本已可以将网关固定为192.168.43.1
