### ISSUE TITLE
热点分享固定IP无效

### ISSUE THREAD

**Issue by kindle939393** [XhyEax/SoftApHelper#7]
热点显示的是192.168.43.1但是在连womic 的时候是失败的，在cfm进入面板也是失效的。虽然IPV4 DNS：192.168.43.1但是就是不知道为什么没有用，作用域都钩了。同样效果 但是别人魔改的192.168.1.1有效  IPV4 dns：192.168.1.1 。手机是红米note11TPRO 安卓12 天机8100

**Comment by XhyEax** [comment]
使用其他软件正常吗？比如开启无线调试后，ADB能否正常连接？

可以试试不过滤包名版本，作用域多勾一些试试？

**Comment by kindle939393** [comment]
> 使用其他软件正常吗？比如开启无线调试后，ADB能否正常连接？
> 
> 可以试试不过滤包名版本，作用域多勾一些试试？

请问作用域还能勾选啥

**Comment by XhyEax** [comment]
含有networkstack的都可以试试。

你先测试其他功能是否正常。比如能否正常上网，WiFi ADB能否连接

**Comment by kindle939393** [comment]
但我希望用其他后缀，因为1.1容易起冲突

**Comment by XhyEax** [comment]
我的意思使用手机开热点，测试其他软件连接192.168.43.1是否正常。

看这个截图用的是1.010版本，应该只改了字符串，你可以试试。
https://github.com/XhyEax/SoftApHelper/releases/download/v1.010/v1.010.apk

或者直接用MT管理器重打包。

**Comment by XhyEax** [comment]
目前没空对比还有哪里不同，发了个重打包版本，你试试。
https://github.com/XhyEax/SoftApHelper/releases/download/v1.010/v1.010-repack.apk

**Comment by kindle939393** [comment]
[config (5).txt](https://github.com/XhyEax/SoftApHelper/files/9769403/config.5.txt)
还是不行，adb链接它给出来的地址是可以的，但是43.1是不行的，这个是我CFM的配置文件，如果没时间的话，那就不多麻烦您了，我就用之前的1.1的使用了，感谢您了

**Comment by XhyEax** [comment]
也就是说，v1.020和以上两个链接的v1.010都不行吗？那挺奇怪的。

**Comment by kindle939393** [comment]
> v1.020和以上两个链接的v1.010都不行吗？那挺奇

是的，1.02的两个版本我也试过了，也是不行

**Comment by XhyEax** [comment]
反编译对比了一下，修改版只是在v1.010的基础上改了ip地址。理论上43.1应该也能用的。
可能系统有啥限制吧。

晚上发个固定192.168.1.1的版本。

后续会加上自定义ip功能。

**Comment by XhyEax** [comment]
已上传192.168.1.1版本，可以试试。

https://github.com/XhyEax/SoftApHelper/releases/tag/v1.020

**Comment by kindle939393** [comment]
> 已上传192.168.1.1版本，可以试试。
> 
> https://github.com/XhyEax/SoftApHelper/releases/tag/v1.020

可以用 试了 应该是我这手机好像就用不了43.1 您的这个1.02版本我重启后 也是可以用的
