### ISSUE TITLE
刷了最新版  热点ip还是改变

### ISSUE THREAD

**Issue by JimmyPOon1** [XhyEax/SoftApHelper#9]
手机真我q2pro 安卓11 刷的最新版 面具25.2 lsp 最新版 lsp勾了系统框架和the  分开单独勾也不行  重启过  热点ip还是随机 不固定

**Comment by XhyEax** [comment]
试了两个non-filter版本吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




 
手机真我q2pro 安卓11 刷的最新版 面具25.2 lsp 最新版 lsp勾了系统框架和the  分开单独勾也不行  重启过  热点ip还是随机 不固定

**Comment by JimmyPOon1** [comment]
> 试了两个non-filter版本吗？
> [...](#)
> ---原始邮件---发件人：***@***.***&gt;发送时间：2022年11月18日（周五）上午9:23收件人：***@***.***&gt;;抄送：***@***.***&gt;;主题：[XhyEax/SoftApHelper]刷了最新版热点ip还是改变（[第9](https://github.com/XhyEax/SoftApHelper/issues/9)期）手机真我q2pro 安卓11 刷最新版 面具25.2 lsp 最新版 lsp勾了系统框架和分开单独勾也不行重启过 热点ip还是随机 不固定—直接回复此电子邮件，在GitHub上查看或取消订阅。您收到此邮件是因为您订阅了此主题。消息ID：***@***.***&gt;

还没 这俩个不一样吗 我听其他大佬说只是有没有推荐作用域的区别

**Comment by XhyEax** [comment]
由于系统原因，以及可能会改包名，导致过滤不生效，所以提供了non-filter版本。
有的手机不支持设置为192.168.43.1，所以提供了1.1版本。


你先测试看看能不能用



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 上午10:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




  
试了两个non-filter版本吗？
 ...
 ***@***.******@***.******@***.***&gt;;主题：[XhyEax/SoftApHelper]刷了最新版热点ip还是改变（第9期）手机真我q2pro 安卓11 刷最新版 面具25.2 lsp 最新版 lsp勾了系统框架和分开单独勾也不行重启过 热点ip还是随机 ***@***.***&gt;
  
还没 这俩个不一样吗 我听其他大佬说只是有没有推荐作用域的区别

**Comment by JimmyPOon1** [comment]
那非过滤版本 作用域还是选择之前的吗  然后需要啥其他操作吗  不是很懂过滤这个概念

**Comment by XhyEax** [comment]
对，作用域不变。(理论上只勾选系统框架就可以了)



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 上午10:15
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




 
是1.1和43.1的 no filter 都试一下是吗

**Comment by XhyEax** [comment]
还是不行的话，把/apex/com.android.tethering/priv-app/文件夹下的apk发上来看看



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 上午9:23
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




 
手机真我q2pro 安卓11 刷的最新版 面具25.2 lsp 最新版 lsp勾了系统框架和the  分开单独勾也不行  重启过  热点ip还是随机 不固定

**Comment by JimmyPOon1** [comment]
我这好像不能上传文件 邮箱给你发不过去呢

**Comment by JimmyPOon1** [comment]
通过百度网盘分享的文件：Tetherin....apk
链接：https://pan.baidu.com/s/17FevWpCJBqcswuRdIbU1Wg 
提取码：9KuW 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by XhyEax** [comment]
网盘



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月18日(周五) 中午12:27
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




 
我这好像不能上传文件 邮箱给你发不过去呢

**Comment by JimmyPOon1** [comment]
能看见吗 我给你发网盘了

**Comment by JimmyPOon1** [comment]
https://pan.baidu.com/s/17FevWpCJBqcswuRdIbU1Wg
提取码：9KuW

**Comment by XhyEax** [comment]
找到原因了，你的系统虽然是11，但是整合了12的热点代码。导致Hook失败，晚上给你修复。

**Comment by JimmyPOon1** [comment]
好的大佬 感谢

**Comment by XhyEax** [comment]
已更新。
[v1.030](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.030)

**Comment by JimmyPOon1** [comment]
热点固定了 但是热点机usb连接路由器 那个路由器没网络呢

**Comment by JimmyPOon1** [comment]
是不是不能usb连接路由器了

**Comment by JimmyPOon1** [comment]
路由器usb显示连接了  但是一直无网络
![Uploading 7E9835AB-8CDB-4945-ADE7-95DFE8D671EF.jpeg…]()

**Comment by XhyEax** [comment]
开热点给其他手机有网络吗

**Comment by JimmyPOon1** [comment]
热点有网  但是usb连接路由器 路由器无网络

**Comment by XhyEax** [comment]
不固定ip，usb连接有网？

**Comment by JimmyPOon1** [comment]
对

**Comment by JimmyPOon1** [comment]
是不是我手机系统原因啊 还是我刷的固件问题

**Comment by XhyEax** [comment]
USB连接后，路由器ping 43.1能通吗

**Comment by XhyEax** [comment]
> 是不是我手机系统原因啊 还是我刷的固件问题

不确定，先测试手机连电脑，开USB共享，有没有网。

**Comment by XhyEax** [comment]
我这边也是安卓11，连接电脑后IP仍固定，且有网。

**Comment by XhyEax** [comment]
你是需要开热点固定，USB连接不固定？

**Comment by XhyEax** [comment]
还是说USB固定与否无所谓，需要有网。

**Comment by JimmyPOon1** [comment]
usb固定无所谓又网就行 但是 热点需要固定

**Comment by JimmyPOon1** [comment]
现在刷了openwrt  不知道咋usb共享

**Comment by XhyEax** [comment]
连windows或者mac电脑之后，手机端开启USB网络共享就行了。
先测试USB热点共享普通电脑有没有网，排除固件影响。

**Comment by JimmyPOon1** [comment]
我现在手里没有电脑 等下午我试试吧

**Comment by JimmyPOon1** [comment]
能usb给ipad吗

**Comment by XhyEax** [comment]
我这边测试发现，如果存在网络前缀冲突的话，是上不了网的。你路由器连接了其他网络吗？或者设置了自己的子网。

**Comment by JimmyPOon1** [comment]
这不是很清楚呢 只usb共享 没其他连接啊 子网不是很清楚

**Comment by XhyEax** [comment]
已发布新版。只对Wifi热点生效。

[v1.040](https://github.com/XhyEax/SoftApHelper/releases/tag/v1.040)

**Comment by JimmyPOon1** [comment]
之前的版本我试了 usb电脑有网 但是路由器没有 估计是路由器问题？

**Comment by JimmyPOon1** [comment]
大佬最新版好像也有问题  要不我加你个方式  直接给你发图和日志

**Comment by JimmyPOon1** [comment]
通过百度网盘分享的文件：2022-11-....png
链接：https://pan.baidu.com/s/1oD9SimN3rhb33k5LxvbzSw 
提取码：6kb8 
复制这段内容打开「百度网盘APP 即可获取」

**Comment by XhyEax** [comment]
最新版USB共享给电脑，IP是否变化。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




 
之前的版本我试了 usb电脑有网 但是路由器没有 估计是路由器问题？

**Comment by JimmyPOon1** [comment]
这个没注意 但是可以共享给电脑  路由器就不行 估计是路由器的问题

**Comment by JimmyPOon1** [comment]
排除了手机问题  但是我不知道路由器原理是什么  我发了那张图片你看看  是哪里有问题 ip的问题还是获取方式不对

**Comment by XhyEax** [comment]
你USB共享给路由器，和共享给电脑，操作是一样的吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年11月19日(周六) 晚上7:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [XhyEax/SoftApHelper] 刷了最新版  热点ip还是改变 (Issue #9)




 
排除了手机问题  但是我不知道路由器原理是什么  我发了那张图片你看看  是哪里有问题 ip的问题还是获取方式不对

**Comment by JimmyPOon1** [comment]
对 给电脑共享我打开了手机usb网络共享  然后路由器也是 唯一不同就是电脑是直接就本地连接就可以 路由器也需要连接但是却感觉获取不到一样

**Comment by XhyEax** [comment]
我这边测试最新版，USB连接已经恢复随机IP了，理论上跟你没开插件是一样的。你连接路由器后，手机执行`ifconfig`，看看IP是不是还是43.1

**Comment by XhyEax** [comment]
> 大佬最新版好像也有问题 要不我加你个方式 直接给你发图和日志

vx: xhyeax

**Comment by XhyEax** [comment]
非模块问题，属于路由器问题。关闭issues。
